### ISSUE TITLE
add pp to /top query

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#422] opened 2023-06-19 07:56 UTC
> would be useful for things like `/top sort:Date query:pp>600`

[Original message by @cd36](https://discord.com/channels/741040473476694159/741047663532834827/1120208136352043049)

**Comment by MaxOhn** [comment] 2023-06-26 14:59
Duplicate of #358

**Closed by MaxOhn** 2023-06-26 14:59 UTC
Labels: suggestion
