### ISSUE TITLE
rlp alias for rl pass=true

### ISSUE THREAD

**Issue by Bathbot-Helper** [MaxOhn/Bathbot#174] opened 2023-02-03 23:36 UTC
> a combination command for rp and rl (= rpl) would be nice

[Source message by @Tommi](https://discord.com/channels/741040473476694159/741047663532834827/1071129426609307718)

**Comment by MaxOhn** [comment] 2023-02-23 10:18
duplicate of #27
closed by #225

**Closed by MaxOhn** 2023-02-23 10:18 UTC
Labels: suggestion
